name: Bug Report
description: File a bug report
title: '[BUG] '
labels: ['bug']
assignees:
  - Sayshal
body:
  - type: markdown
    attributes:
      value: |
        Use this form to report an issue with the module. Please fill out all the fields to the best of your ability.
  - type: checkboxes
    id: troubleshooter
    attributes:
      label: Hero Mancer Troubleshooter
      description: Recreate the issue being reported in Hero Mancer, and without closing the application, open the troubleshooter from the Settings menu. Download the troubleshooter file and attach it below.
      options:
        - label: I understand that I will not recieve support until a troubleshooter file has been uploaded.
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
